### ISSUE TITLE
Request Your Compile Step

### ISSUE THREAD

**Issue by GoodDay360** [MarshallSCPT/Cheat-Engine-Bypass#1]
- It would be nice if you could provide us with step by step of how you custom compile Cheat Engine.
- There probably a lots of tutorial out there but it seem like most of them end up in error or still detected by anticheat after self compiled.
- We would like to know your way of doing it. So we could edit some title,string,etc... since sooner or later this engine will be flagged in anticheat. 
Thanks for your hard work 👍

**Comment by MarshallSCPT** [comment]
Hi, thanks for the encouragement. 
I'm currently using the Lazarus program to compile the Cheat Engine, I always recommend getting the most up-to-date version of the program and performing the standard installation, if you experience any compilation errors, let me know here and we'll see a way to solve it!
